#! /bin/sh

bspc config border_width        2
bspc config window_gap          0

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc rule -a Firefox desktop=^8
bspc rule -a qutebrowser desktop=^8
bspc rule -a feh floating=on
bspc rule -a pavucontrol floating=on

 ${HOME}/.config/bspwm/panel